/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package so1;

/**
 *
 * @author Marcos
 */
public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btnE18000_8 = new javax.swing.JButton();
        btnE18000_9 = new javax.swing.JButton();
        btnE18000_10 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnE18000_1 = new javax.swing.JButton();
        btnE18000_2 = new javax.swing.JButton();
        btnE18000_3 = new javax.swing.JButton();
        btnE18000_4 = new javax.swing.JButton();
        btnE18000_5 = new javax.swing.JButton();
        btnE18000_6 = new javax.swing.JButton();
        btnE18000_7 = new javax.swing.JButton();
        btnE12000_1 = new javax.swing.JButton();
        btnE12000_2 = new javax.swing.JButton();
        btnE12000_3 = new javax.swing.JButton();
        btnE12000_4 = new javax.swing.JButton();
        btnE12000_5 = new javax.swing.JButton();
        btnE12000_6 = new javax.swing.JButton();
        btnE12000_7 = new javax.swing.JButton();
        btnE12000_8 = new javax.swing.JButton();
        btnE12000_9 = new javax.swing.JButton();
        btnE12000_10 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnE5000_10 = new javax.swing.JButton();
        btnE5000_9 = new javax.swing.JButton();
        btnE5000_8 = new javax.swing.JButton();
        btnE5000_7 = new javax.swing.JButton();
        btnE5000_6 = new javax.swing.JButton();
        btnE5000_5 = new javax.swing.JButton();
        btnE5000_4 = new javax.swing.JButton();
        btnE5000_3 = new javax.swing.JButton();
        btnE5000_2 = new javax.swing.JButton();
        btnE5000_1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnPd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnE20000_1 = new javax.swing.JButton();
        btnE20000_2 = new javax.swing.JButton();
        btnE20000_3 = new javax.swing.JButton();
        btnE20000_4 = new javax.swing.JButton();
        btnE20000_5 = new javax.swing.JButton();
        btnE20000_6 = new javax.swing.JButton();
        btnE20000_7 = new javax.swing.JButton();
        btnE20000_8 = new javax.swing.JButton();
        btnE20000_9 = new javax.swing.JButton();
        btnE20000_10 = new javax.swing.JButton();
        btnE15000_10 = new javax.swing.JButton();
        btnE15000_9 = new javax.swing.JButton();
        btnE15000_8 = new javax.swing.JButton();
        btnE15000_7 = new javax.swing.JButton();
        btnE15000_6 = new javax.swing.JButton();
        btnE15000_5 = new javax.swing.JButton();
        btnE15000_4 = new javax.swing.JButton();
        btnE15000_3 = new javax.swing.JButton();
        btnE15000_2 = new javax.swing.JButton();
        btnE15000_1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnE10000_10 = new javax.swing.JButton();
        btnE10000_1 = new javax.swing.JButton();
        btnE10000_5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnE10000_9 = new javax.swing.JButton();
        btnE10000_8 = new javax.swing.JButton();
        btnE10000_7 = new javax.swing.JButton();
        btnE10000_6 = new javax.swing.JButton();
        btnE10000_4 = new javax.swing.JButton();
        btnE10000_3 = new javax.swing.JButton();
        btnE10000_2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnPp = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnE18000_8.setBackground(new java.awt.Color(255, 255, 255));
        btnE18000_8.setForeground(new java.awt.Color(255, 255, 255));
        btnE18000_8.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE18000_8.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE18000_9.setBackground(new java.awt.Color(255, 255, 255));
        btnE18000_9.setForeground(new java.awt.Color(255, 255, 255));
        btnE18000_9.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE18000_9.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE18000_10.setBackground(new java.awt.Color(255, 255, 255));
        btnE18000_10.setForeground(new java.awt.Color(255, 255, 255));
        btnE18000_10.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE18000_10.setMinimumSize(new java.awt.Dimension(27, 27));

        jLabel5.setText("E18000");

        btnE18000_1.setBackground(new java.awt.Color(255, 255, 255));
        btnE18000_1.setForeground(new java.awt.Color(255, 255, 255));
        btnE18000_1.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE18000_1.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE18000_2.setBackground(new java.awt.Color(255, 255, 255));
        btnE18000_2.setForeground(new java.awt.Color(255, 255, 255));
        btnE18000_2.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE18000_2.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE18000_3.setBackground(new java.awt.Color(255, 255, 255));
        btnE18000_3.setForeground(new java.awt.Color(255, 255, 255));
        btnE18000_3.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE18000_3.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE18000_4.setBackground(new java.awt.Color(255, 255, 255));
        btnE18000_4.setForeground(new java.awt.Color(255, 255, 255));
        btnE18000_4.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE18000_4.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE18000_5.setBackground(new java.awt.Color(255, 255, 255));
        btnE18000_5.setForeground(new java.awt.Color(255, 255, 255));
        btnE18000_5.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE18000_5.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE18000_6.setBackground(new java.awt.Color(255, 255, 255));
        btnE18000_6.setForeground(new java.awt.Color(255, 255, 255));
        btnE18000_6.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE18000_6.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE18000_7.setBackground(new java.awt.Color(255, 255, 255));
        btnE18000_7.setForeground(new java.awt.Color(255, 255, 255));
        btnE18000_7.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE18000_7.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE12000_1.setBackground(new java.awt.Color(255, 255, 255));
        btnE12000_1.setForeground(new java.awt.Color(255, 255, 255));
        btnE12000_1.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE12000_1.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE12000_2.setBackground(new java.awt.Color(255, 255, 255));
        btnE12000_2.setForeground(new java.awt.Color(255, 255, 255));
        btnE12000_2.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE12000_2.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE12000_3.setBackground(new java.awt.Color(255, 255, 255));
        btnE12000_3.setForeground(new java.awt.Color(255, 255, 255));
        btnE12000_3.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE12000_3.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE12000_4.setBackground(new java.awt.Color(255, 255, 255));
        btnE12000_4.setForeground(new java.awt.Color(255, 255, 255));
        btnE12000_4.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE12000_4.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE12000_5.setBackground(new java.awt.Color(255, 255, 255));
        btnE12000_5.setForeground(new java.awt.Color(255, 255, 255));
        btnE12000_5.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE12000_5.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE12000_6.setBackground(new java.awt.Color(255, 255, 255));
        btnE12000_6.setForeground(new java.awt.Color(255, 255, 255));
        btnE12000_6.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE12000_6.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE12000_7.setBackground(new java.awt.Color(255, 255, 255));
        btnE12000_7.setForeground(new java.awt.Color(255, 255, 255));
        btnE12000_7.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE12000_7.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE12000_8.setBackground(new java.awt.Color(255, 255, 255));
        btnE12000_8.setForeground(new java.awt.Color(255, 255, 255));
        btnE12000_8.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE12000_8.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE12000_9.setBackground(new java.awt.Color(255, 255, 255));
        btnE12000_9.setForeground(new java.awt.Color(255, 255, 255));
        btnE12000_9.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE12000_9.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE12000_10.setBackground(new java.awt.Color(255, 255, 255));
        btnE12000_10.setForeground(new java.awt.Color(255, 255, 255));
        btnE12000_10.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE12000_10.setMinimumSize(new java.awt.Dimension(27, 27));

        jLabel6.setText("E12000");

        btnE5000_10.setBackground(new java.awt.Color(255, 255, 255));
        btnE5000_10.setForeground(new java.awt.Color(255, 255, 255));
        btnE5000_10.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE5000_10.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE5000_9.setBackground(new java.awt.Color(255, 255, 255));
        btnE5000_9.setForeground(new java.awt.Color(255, 255, 255));
        btnE5000_9.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE5000_9.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE5000_8.setBackground(new java.awt.Color(255, 255, 255));
        btnE5000_8.setForeground(new java.awt.Color(255, 255, 255));
        btnE5000_8.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE5000_8.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE5000_7.setBackground(new java.awt.Color(255, 255, 255));
        btnE5000_7.setForeground(new java.awt.Color(255, 255, 255));
        btnE5000_7.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE5000_7.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE5000_6.setBackground(new java.awt.Color(255, 255, 255));
        btnE5000_6.setForeground(new java.awt.Color(255, 255, 255));
        btnE5000_6.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE5000_6.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE5000_5.setBackground(new java.awt.Color(255, 255, 255));
        btnE5000_5.setForeground(new java.awt.Color(255, 255, 255));
        btnE5000_5.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE5000_5.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE5000_4.setBackground(new java.awt.Color(255, 255, 255));
        btnE5000_4.setForeground(new java.awt.Color(255, 255, 255));
        btnE5000_4.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE5000_4.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE5000_3.setBackground(new java.awt.Color(255, 255, 255));
        btnE5000_3.setForeground(new java.awt.Color(255, 255, 255));
        btnE5000_3.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE5000_3.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE5000_2.setBackground(new java.awt.Color(255, 255, 255));
        btnE5000_2.setForeground(new java.awt.Color(255, 255, 255));
        btnE5000_2.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE5000_2.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE5000_1.setBackground(new java.awt.Color(255, 255, 255));
        btnE5000_1.setForeground(new java.awt.Color(255, 255, 255));
        btnE5000_1.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE5000_1.setMinimumSize(new java.awt.Dimension(27, 27));

        jLabel7.setText("E5000");

        jLabel8.setText("Pista de Decolagem");

        btnPd.setBackground(new java.awt.Color(255, 255, 255));
        btnPd.setForeground(new java.awt.Color(255, 255, 255));
        btnPd.setMaximumSize(new java.awt.Dimension(35, 35));
        btnPd.setMinimumSize(new java.awt.Dimension(27, 27));

        jLabel9.setText("E20000");

        btnE20000_1.setBackground(new java.awt.Color(255, 255, 255));
        btnE20000_1.setForeground(new java.awt.Color(255, 255, 255));
        btnE20000_1.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE20000_1.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE20000_2.setBackground(new java.awt.Color(255, 255, 255));
        btnE20000_2.setForeground(new java.awt.Color(255, 255, 255));
        btnE20000_2.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE20000_2.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE20000_3.setBackground(new java.awt.Color(255, 255, 255));
        btnE20000_3.setForeground(new java.awt.Color(255, 255, 255));
        btnE20000_3.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE20000_3.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE20000_4.setBackground(new java.awt.Color(255, 255, 255));
        btnE20000_4.setForeground(new java.awt.Color(255, 255, 255));
        btnE20000_4.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE20000_4.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE20000_5.setBackground(new java.awt.Color(255, 255, 255));
        btnE20000_5.setForeground(new java.awt.Color(255, 255, 255));
        btnE20000_5.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE20000_5.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE20000_6.setBackground(new java.awt.Color(255, 255, 255));
        btnE20000_6.setForeground(new java.awt.Color(255, 255, 255));
        btnE20000_6.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE20000_6.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE20000_7.setBackground(new java.awt.Color(255, 255, 255));
        btnE20000_7.setForeground(new java.awt.Color(255, 255, 255));
        btnE20000_7.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE20000_7.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE20000_8.setBackground(new java.awt.Color(255, 255, 255));
        btnE20000_8.setForeground(new java.awt.Color(255, 255, 255));
        btnE20000_8.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE20000_8.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE20000_9.setBackground(new java.awt.Color(255, 255, 255));
        btnE20000_9.setForeground(new java.awt.Color(255, 255, 255));
        btnE20000_9.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE20000_9.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE20000_10.setBackground(new java.awt.Color(255, 255, 255));
        btnE20000_10.setForeground(new java.awt.Color(255, 255, 255));
        btnE20000_10.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE20000_10.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE15000_10.setBackground(new java.awt.Color(255, 255, 255));
        btnE15000_10.setForeground(new java.awt.Color(255, 255, 255));
        btnE15000_10.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE15000_10.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE15000_9.setBackground(new java.awt.Color(255, 255, 255));
        btnE15000_9.setForeground(new java.awt.Color(255, 255, 255));
        btnE15000_9.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE15000_9.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE15000_8.setBackground(new java.awt.Color(255, 255, 255));
        btnE15000_8.setForeground(new java.awt.Color(255, 255, 255));
        btnE15000_8.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE15000_8.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE15000_7.setBackground(new java.awt.Color(255, 255, 255));
        btnE15000_7.setForeground(new java.awt.Color(255, 255, 255));
        btnE15000_7.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE15000_7.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE15000_6.setBackground(new java.awt.Color(255, 255, 255));
        btnE15000_6.setForeground(new java.awt.Color(255, 255, 255));
        btnE15000_6.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE15000_6.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE15000_5.setBackground(new java.awt.Color(255, 255, 255));
        btnE15000_5.setForeground(new java.awt.Color(255, 255, 255));
        btnE15000_5.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE15000_5.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE15000_4.setBackground(new java.awt.Color(255, 255, 255));
        btnE15000_4.setForeground(new java.awt.Color(255, 255, 255));
        btnE15000_4.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE15000_4.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE15000_3.setBackground(new java.awt.Color(255, 255, 255));
        btnE15000_3.setForeground(new java.awt.Color(255, 255, 255));
        btnE15000_3.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE15000_3.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE15000_2.setBackground(new java.awt.Color(255, 255, 255));
        btnE15000_2.setForeground(new java.awt.Color(255, 255, 255));
        btnE15000_2.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE15000_2.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE15000_1.setBackground(new java.awt.Color(255, 255, 255));
        btnE15000_1.setForeground(new java.awt.Color(255, 255, 255));
        btnE15000_1.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE15000_1.setMinimumSize(new java.awt.Dimension(27, 27));

        jLabel10.setText("E15000");

        btnE10000_10.setBackground(new java.awt.Color(255, 255, 255));
        btnE10000_10.setForeground(new java.awt.Color(255, 255, 255));
        btnE10000_10.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE10000_10.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE10000_1.setBackground(new java.awt.Color(255, 255, 255));
        btnE10000_1.setForeground(new java.awt.Color(255, 255, 255));
        btnE10000_1.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE10000_1.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE10000_5.setBackground(new java.awt.Color(255, 255, 255));
        btnE10000_5.setForeground(new java.awt.Color(255, 255, 255));
        btnE10000_5.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE10000_5.setMinimumSize(new java.awt.Dimension(27, 27));

        jLabel11.setText("E10000");

        btnE10000_9.setBackground(new java.awt.Color(255, 255, 255));
        btnE10000_9.setForeground(new java.awt.Color(255, 255, 255));
        btnE10000_9.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE10000_9.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE10000_8.setBackground(new java.awt.Color(255, 255, 255));
        btnE10000_8.setForeground(new java.awt.Color(255, 255, 255));
        btnE10000_8.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE10000_8.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE10000_7.setBackground(new java.awt.Color(255, 255, 255));
        btnE10000_7.setForeground(new java.awt.Color(255, 255, 255));
        btnE10000_7.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE10000_7.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE10000_6.setBackground(new java.awt.Color(255, 255, 255));
        btnE10000_6.setForeground(new java.awt.Color(255, 255, 255));
        btnE10000_6.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE10000_6.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE10000_4.setBackground(new java.awt.Color(255, 255, 255));
        btnE10000_4.setForeground(new java.awt.Color(255, 255, 255));
        btnE10000_4.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE10000_4.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE10000_3.setBackground(new java.awt.Color(255, 255, 255));
        btnE10000_3.setForeground(new java.awt.Color(255, 255, 255));
        btnE10000_3.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE10000_3.setMinimumSize(new java.awt.Dimension(27, 27));

        btnE10000_2.setBackground(new java.awt.Color(255, 255, 255));
        btnE10000_2.setForeground(new java.awt.Color(255, 255, 255));
        btnE10000_2.setMaximumSize(new java.awt.Dimension(35, 35));
        btnE10000_2.setMinimumSize(new java.awt.Dimension(27, 27));

        jLabel12.setText("Pista de Pouso");

        btnPp.setBackground(new java.awt.Color(255, 255, 255));
        btnPp.setForeground(new java.awt.Color(255, 255, 255));
        btnPp.setMaximumSize(new java.awt.Dimension(35, 35));
        btnPp.setMinimumSize(new java.awt.Dimension(27, 27));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE10000_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE10000_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE10000_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE10000_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE10000_5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE10000_6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE10000_7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE10000_8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE10000_9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE10000_10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE15000_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE15000_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE15000_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE15000_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE15000_5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE15000_6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE15000_7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE15000_8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE15000_9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE15000_10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE18000_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE18000_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE18000_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE18000_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE18000_5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE18000_6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE18000_7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE18000_8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE18000_9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE18000_10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE12000_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE12000_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE12000_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE12000_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE12000_5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE12000_6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE12000_7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE12000_8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE12000_9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE12000_10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE5000_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE5000_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE5000_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE5000_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE5000_5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE5000_6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE5000_7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE5000_8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE5000_9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnE5000_10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(461, 461, 461)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnE20000_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnE20000_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnE20000_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnE20000_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnE20000_5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnE20000_6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnE20000_7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnE20000_8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnE20000_9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnE20000_10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(160, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(340, 340, 340))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnE20000_5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnE20000_4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnE20000_3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnE20000_2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnE20000_1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addComponent(btnE20000_10, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnE20000_9, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnE20000_8, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnE20000_6, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnE20000_7, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnE18000_5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnE18000_4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnE18000_3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnE18000_2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnE18000_1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(btnE18000_10, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnE18000_9, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnE18000_8, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnE18000_6, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnE18000_7, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnE15000_5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE15000_4, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE15000_3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE15000_2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE15000_1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(btnE15000_10, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE15000_9, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE15000_8, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE15000_6, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE15000_7, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnE12000_5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE12000_4, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE12000_3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE12000_2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE12000_1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(btnE12000_10, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE12000_9, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE12000_8, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE12000_6, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE12000_7, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnE10000_5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE10000_4, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE10000_3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE10000_2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE10000_1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addComponent(btnE10000_10, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE10000_9, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE10000_8, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE10000_6, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE10000_7, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnE5000_5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE5000_4, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE5000_3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE5000_2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE5000_1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(btnE5000_10, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE5000_9, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE5000_8, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE5000_6, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnE5000_7, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPd, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(btnPp, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addGap(148, 148, 148))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }
    

   /* public void setFdText(String teste) {
        fdField.setText(teste);
    }
    
    public void setPdText(String teste) {
        pdField.setText(teste);
    }
    
    public void setPpText(String texto) {
        ppField.setText(texto);
    }
    
    public void setE500Text(String teste) {
        e5000Field.setText(teste);
    }
    
    public void setE12000Text(String texto) {
        e12000Field.setText(texto);
    }
    
    public void setE18000Text(String texto) {
        e18000Field.setText(texto);
    }
    
    public void setE20000Text(String texto) {
        e20000Field.setText(texto);
    }
    
    public void setE15000Text(String texto) {
        e15000Field.setText(texto);
    }
    
    public void setE10000Text(String texto) {
        e10000.setText(texto);
    }*/
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnE10000_1;
    public javax.swing.JButton btnE10000_10;
    public javax.swing.JButton btnE10000_2;
    public javax.swing.JButton btnE10000_3;
    public javax.swing.JButton btnE10000_4;
    public javax.swing.JButton btnE10000_5;
    public javax.swing.JButton btnE10000_6;
    public javax.swing.JButton btnE10000_7;
    public javax.swing.JButton btnE10000_8;
    public javax.swing.JButton btnE10000_9;
    public javax.swing.JButton btnE12000_1;
    public javax.swing.JButton btnE12000_10;
    public javax.swing.JButton btnE12000_2;
    public javax.swing.JButton btnE12000_3;
    public javax.swing.JButton btnE12000_4;
    public javax.swing.JButton btnE12000_5;
    public javax.swing.JButton btnE12000_6;
    public javax.swing.JButton btnE12000_7;
    public javax.swing.JButton btnE12000_8;
    public javax.swing.JButton btnE12000_9;
    public javax.swing.JButton btnE15000_1;
    public javax.swing.JButton btnE15000_10;
    public javax.swing.JButton btnE15000_2;
    public javax.swing.JButton btnE15000_3;
    public javax.swing.JButton btnE15000_4;
    public javax.swing.JButton btnE15000_5;
    public javax.swing.JButton btnE15000_6;
    public javax.swing.JButton btnE15000_7;
    public javax.swing.JButton btnE15000_8;
    public javax.swing.JButton btnE15000_9;
    public javax.swing.JButton btnE18000_1;
    public javax.swing.JButton btnE18000_10;
    public javax.swing.JButton btnE18000_2;
    public javax.swing.JButton btnE18000_3;
    public javax.swing.JButton btnE18000_4;
    public javax.swing.JButton btnE18000_5;
    public javax.swing.JButton btnE18000_6;
    public javax.swing.JButton btnE18000_7;
    public javax.swing.JButton btnE18000_8;
    public javax.swing.JButton btnE18000_9;
    public javax.swing.JButton btnE20000_1;
    public javax.swing.JButton btnE20000_10;
    public javax.swing.JButton btnE20000_2;
    public javax.swing.JButton btnE20000_3;
    public javax.swing.JButton btnE20000_4;
    public javax.swing.JButton btnE20000_5;
    public javax.swing.JButton btnE20000_6;
    public javax.swing.JButton btnE20000_7;
    public javax.swing.JButton btnE20000_8;
    public javax.swing.JButton btnE20000_9;
    public javax.swing.JButton btnE5000_1;
    public javax.swing.JButton btnE5000_10;
    public javax.swing.JButton btnE5000_2;
    public javax.swing.JButton btnE5000_3;
    public javax.swing.JButton btnE5000_4;
    public javax.swing.JButton btnE5000_5;
    public javax.swing.JButton btnE5000_6;
    public javax.swing.JButton btnE5000_7;
    public javax.swing.JButton btnE5000_8;
    public javax.swing.JButton btnE5000_9;
    public javax.swing.JButton btnPd;
    public javax.swing.JButton btnPp;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
